# Generated by Django 3.1 on 2020-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('ciudad', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
